"""Membangun laporan Markdown dan HTML, serta menyimpannya."""

def build_markdown_report(records):
    header = "# Rekap Nilai Mahasiswa\n\n"
    header += "| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |\n"
    header += "|---|---|---:|---:|:---:|\n"
    lines = [header]
    for r in records:
        lines.append(f"| {r['nim']} | {r['nama']} | {r['hadir']:.1f} | {r['nilai_akhir']:.2f} | {r['predikat']} |")
    lines.append("\nGenerated by student_performance_tracker")
    return "\n".join(lines)

def build_html_report(records):
    """Bangun laporan HTML dengan warna berdasarkan predikat."""
    html = """
    <html><head><meta charset='UTF-8'><title>Rekap Nilai</title>
    <style>
        table {border-collapse: collapse; width: 80%; margin: 20px auto;}
        th, td {border: 1px solid #666; padding: 8px; text-align: center;}
        th {background-color: #333; color: white;}
        .A {background-color: #a5d6a7;}
        .B {background-color: #c5e1a5;}
        .C {background-color: #fff59d;}
        .D {background-color: #ffcc80;}
        .E {background-color: #ef9a9a;}
    </style></head><body>
    <h2 style='text-align:center;'>Rekap Nilai Mahasiswa</h2>
    <table>
        <tr><th>NIM</th><th>Nama</th><th>Hadir (%)</th><th>Nilai Akhir</th><th>Predikat</th></tr>
    """
    for r in records:
        html += f"<tr class='{r['predikat']}'><td>{r['nim']}</td><td>{r['nama']}</td><td>{r['hadir']:.1f}</td><td>{r['nilai_akhir']:.2f}</td><td>{r['predikat']}</td></tr>"
    html += "</table><p style='text-align:center;'>Generated by student_performance_tracker</p></body></html>"
    return html

def save_text(path, content):
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
